### PR TITLE
Created wiring diagram for TX2+Orbitty to Pixracer.

### PR DESCRIPTION
**Pull request by rhaksar**

### CODE REVIEW

**Review by exoticDFT — COMMENTED** [review]
The page is looking good!

Did we want to have a wiring diagram figure for the documentation as well? Also I could see the table being a little more clear if we could somehow emphasize there are two sides in the table. Maybe a bolder line down the center of the table or maybe creating another header combining the two columns that represent each device. I am not sure if the bolder line is possible, but I found this on spanning multi-columns https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#tables.

**Comment by rhaksar** [comment]
@exoticDFT I updated the table to hopefully clarify the connections. I can add a picture as well but I think we should figure out a scheme for how we want to host media first.

**Comment by ericcristofalo** [comment]
I like this page; it's clear and concise. I do agree with Alex that a wiring diagram or image of the actual board would be very useful for someone new to the quad.

**Review by ericcristofalo — APPROVED** [review]
I like this page; it's clear and concise. I do agree with Alex that a wiring diagram or image of the actual board would be very useful for someone new to the quad.

**Review by exoticDFT — COMMENTED** [review]
I think that addition makes it a bit more clear. If we aren't doing an actual diagram, I think this is good to go. If we are, I'm not sure what you'd like to use, but I found this tool that seemed pretty cool for wiring diagrams. Might be worth checking out. https://github.com/formatc1702/WireViz

**Comment by exoticDFT** [comment]
@rhaksar @ericcristofalo I decided to try out the tool I mentioned. It automatically creates a few things, html file, png, svg, BOM, etc. Here's a screenshot of the html it creates.
Wiring_html
If we want to use this software, I can send you the yml and we can decide where to put it and therefore the files it will auto create.
I also don't know if the finer details are correct in this yml, but it should be easy to adjust.

**Comment by rhaksar** [comment]
@exoticDFT I like the diagrams made by WireViz but I think it would be more helpful to have pictures of the actual headers on the carrier board and the flight controller, for people who are new to the quad setup. I'm in favor of merging now, and coming back and adding pictures once we verify the setup works.

**Comment by rhaksar** [comment]
I added pictures for the wiring diagrams, let me know what you think.

**Comment by exoticDFT** [comment]
@rhaksar Pictures look awesome! I think it adds a lot of clarity to the section.

Couple of really minor things. This is mostly style guide stuff.
- Where possible, the character limit is 79 per line.
- There should be a return line after a section header (I think this doesn't generally matter, but I believe I saw some comments that not having the blank line can sometimes cause issues.)
- Since you have a warning notification you can use the '.. warning::` directive to give an actual warning box.

**Comment by exoticDFT** [comment]
@rhaksar Looks great let's merge it!

**Pull request merged**
